## 基本的索引与切片

In [2]:
## Python2.7
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5]

5

In [6]:
arr[5:8] = 12

In [7]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

数组的切片是原始数据的视图，这意味着数据不会被复制，视图上的所有修改会反应到源数组上

In [8]:
arr_slice = arr[5:8]

In [9]:
arr_slice[1] = 12345

In [10]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

对于高维数组，各索引位置上的元素不再是标量而是一维数组：

In [12]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

以下两种访问元素的方式是等价的：

In [13]:
print arr2d[0][2]
print arr2d[0, 2]

3
3


在高位数组中，如果省略了后面的索引，则返回对象会是一个维度低一点的ndarray（它包含高一级轴上的所有数据）。

下面的例子是一个$2 \times 2 \times 3$的例子，其可以理解成2个$2 \times 3$的数组。式子最左边代表最高维，最右边代表最低维。

In [14]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [15]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr3d.shape

(2L, 2L, 3L)

标量值和数组都可以被赋值给arr3d[0]（不会改变原数组的形状，维度不足的进行广播，维度超出原先范围，则报错）

In [17]:
old_values = arr3d[0].copy()
arr3d[0] = 43

In [18]:
arr3d

array([[[43, 43, 43],
        [43, 43, 43]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
test = np.array([4, 8, 3, 5])
arr3d[0] = test
arr3d

ValueError: could not broadcast input array from shape (4) into shape (2,3)

In [24]:
arr3d[1, 0]

array([7, 8, 9])

In [25]:
arr3d[1, 0, 2]

9

### 切片索引

对二维数组执行切片操作，当只给出一个索引值时，此索引值代表最高维度的那个轴，即第0轴。

In [34]:
arr2d[2:]

array([[7, 8, 9]])

下面的情况就是分别在第0轴和第1轴上执行切片操作。

In [39]:
arr2d[:2, 1:]  # 0轴从头取到第1位（:2左闭右开，取不到第2位），1轴从第一位取到最后一位

array([[2, 3],
       [5, 6]])

下面的操作只取特定轴上的特定元素

In [35]:
arr2d[2, 1] # 零轴只取第2位，1轴只取第1位

8

下面的操作对特定的轴取切片操作

In [36]:
arr2d[:2, 1]  # 零轴从头取到第1位，一轴只取第1位

array([2, 5])

只加冒号代表索引整个轴。

In [30]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [32]:
arr3d[:1]

array([[[4, 8, 3],
        [4, 8, 3]]])

### 布尔型索引

假设有一个用于存储数据的数组以及一个存储姓名的数组（含有重复项）。这里，我们使用np.random.randn([shape])函数生成一些正太分布的随机数据：

In [40]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [41]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='|S4')

In [42]:
data

array([[ 0.95685817, -1.09410319, -1.37397005, -0.63375788],
       [ 0.33263869, -0.53507432, -1.28676437,  1.01602618],
       [ 1.20620671,  1.37793124, -0.7702841 ,  0.73165662],
       [ 0.2554341 ,  0.84910328,  1.42403747,  0.30950998],
       [-0.93802236, -0.66729157, -1.39806755, -0.12863794],
       [-1.08383097,  0.84208288, -0.40168278,  1.70952463],
       [-0.28093381,  0.11304535, -0.8661587 , -0.67375262]])

假设每个名字都对应data数组中的一行，而我们想拣选出对应于名字'Bob'的所有行。

In [43]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [45]:
data[names == 'Bob']  # 只显示索引为True的元素。

array([[ 0.95685817, -1.09410319, -1.37397005, -0.63375788],
       [ 0.2554341 ,  0.84910328,  1.42403747,  0.30950998]])

In [50]:
data[names == 'Bob', 3:]  # 在低维轴的边缘加冒号会保留高维轴的值，
                          # 此处高维轴（代表行数的轴）为2被保留。

array([[-0.63375788],
       [ 0.30950998]])

In [48]:
data[names == 'Bob', 3]  # 这里不带冒号，高维轴的值被抹去，返回的值重新组成一个新的低维数组，但其中元素仍是源数组元素的视图。

array([-0.63375788,  0.30950998])

同理可得：

In [51]:
data[names == 'Bob', :1]

array([[ 0.95685817],
       [ 0.2554341 ]])

In [53]:
data[names == 'Bob', 0]

array([ 0.95685817,  0.2554341 ])

可以使用不等号（!=）或负号（-）对条件进行否定，来选取'Bob'以外的其他值。

In [55]:
data[names != 'Bob']

array([[ 0.33263869, -0.53507432, -1.28676437,  1.01602618],
       [ 1.20620671,  1.37793124, -0.7702841 ,  0.73165662],
       [-0.93802236, -0.66729157, -1.39806755, -0.12863794],
       [-1.08383097,  0.84208288, -0.40168278,  1.70952463],
       [-0.28093381,  0.11304535, -0.8661587 , -0.67375262]])

In [56]:
data[-(names == 'Bob')]

C:\Anaconda3\envs\python2.7\lib\site-packages\ipykernel\__main__.py:1: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
  if __name__ == '__main__':


array([[ 0.33263869, -0.53507432, -1.28676437,  1.01602618],
       [ 1.20620671,  1.37793124, -0.7702841 ,  0.73165662],
       [-0.93802236, -0.66729157, -1.39806755, -0.12863794],
       [-1.08383097,  0.84208288, -0.40168278,  1.70952463],
       [-0.28093381,  0.11304535, -0.8661587 , -0.67375262]])

**布尔算术符** &：和， |：或，等等。**警告**，Python关键字and和or在布尔型数组中无效。 

In [57]:
mask = (names == 'Bob') | (names == 'Will')
data[mask]

array([[ 0.95685817, -1.09410319, -1.37397005, -0.63375788],
       [ 1.20620671,  1.37793124, -0.7702841 ,  0.73165662],
       [ 0.2554341 ,  0.84910328,  1.42403747,  0.30950998],
       [-0.93802236, -0.66729157, -1.39806755, -0.12863794]])

通过布尔型数组设置值是一种经常用到的手段。

In [59]:
data[data < 0] = 0
data

array([[ 0.95685817,  0.        ,  0.        ,  0.        ],
       [ 0.33263869,  0.        ,  0.        ,  1.01602618],
       [ 1.20620671,  1.37793124,  0.        ,  0.73165662],
       [ 0.2554341 ,  0.84910328,  1.42403747,  0.30950998],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.84208288,  0.        ,  1.70952463],
       [ 0.        ,  0.11304535,  0.        ,  0.        ]])

In [60]:
data[names != 'Joe'] = 7
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.33263869,  0.        ,  0.        ,  1.01602618],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.84208288,  0.        ,  1.70952463],
       [ 0.        ,  0.11304535,  0.        ,  0.        ]])

### 花式索引

花式索引（Fansy indexing）是一个numpy术语，指的是利用整数数组进行索引。

In [5]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

为了以特定顺序选取行子集，只需传入一个用于指定顺序的整数列表或ndarray即可

In [6]:
arr[[4, 3, 0, 6]]  # 分别选群第4， 3， 0 ，6行

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [8]:
 arr[[-3, -5, -7]]  # 分别选取第5， 3， 1行

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

一次传入多个索引数组会有一点特别。它返回的是一个一维数组，其中的元素对应各个索引元组：

In [9]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [10]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

最终选取的元素是(1, 0), (5, 3), (7, 1), (2, 2)。这个结果跟预期不一样。选取子集的行列子集应该是矩形区域才对？ 下面是得到矩形区域的一个办法：

In [11]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]  # 选取1，5，7，2行，与0,3,1,2列的交集

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

还一个办法是使用np.ix\_函数，它可以将两个一维整数数组转换为一个用于选取方形区域的所引器：

In [12]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## 数组的转置和轴对换

转置（transpose）是重塑的一种特殊形式，它返回的是源数据的视图。

In [13]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [15]:
np.dot(arr.T, arr)  # 计算矩阵内积

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

对于高维数组，transpose需要得到一个由轴编号组成的元组才能对这些轴进行转置（比较费脑子）。

In [18]:
arr = np.arange(16).reshape((2, 2, 4))  # 2个2 x 4的数表
arr  # 此时轴编号为(0, 1, 2)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [19]:
arr.transpose((1,0,2))  # 保持2轴不变，转置0轴和1轴

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [20]:
arr.transpose((0,2,1))  # 保持0轴不变，转置1轴和2轴

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

简单的转置可以使用.T，其实就是对轴进行对换。ndarray还有一个swapaxes方法，它需要接受**一对**轴编号：

In [21]:
arr.swapaxes(1, 2)  # 转置1轴和2轴

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## 通用函数：快速的元素级数组函数

ufunc是一种对ndarray中的数据执行元素级运算的函数。可以将其看作简单函数的矢量化包装器。

In [22]:
arr = np.arange(10)
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [25]:
x = np.random.randn(8)
y = np.random.randn(8)

In [26]:
x

array([-0.6412223 ,  0.2128255 ,  1.16720496, -1.04440516, -0.25562211,
        0.74170332,  0.03483926, -0.65818645])

In [27]:
y

array([ 0.94567794,  0.47832173,  1.19747474,  0.39129313, -1.07825235,
        0.16609234, -0.76159507, -0.22657381])

In [28]:
np.maximum(x, y)  # 元素级别的返回最大值，并组成新数组。

array([ 0.94567794,  0.47832173,  1.19747474,  0.39129313, -0.25562211,
        0.74170332,  0.03483926, -0.22657381])

In [29]:
arr = np.random.randn(8) * 5
np.modf(arr)  # 这事内建函数divmod的矢量化版本，用于筛选浮点数

(array([ 0.41820112,  0.14998407,  0.57781883,  0.19896936,  0.83866474,
        -0.90228025,  0.59767295,  0.89767392]),
 array([  2.,   2.,  16.,   1.,   4.,  -8.,   1.,   1.]))